version: 2

build:
  os: "ubuntu-22.04"  # Вказуємо одну з підтримуваних версій ОС
  tools:
    python: "3.8"  # Вказуємо версію Python для побудови документації

sphinx:
  configuration: "docs/conf.py"  # Вказуємо конфігурацію для Sphinx, якщо це необхідно

python:
  install:
    - requirements: "docs/requirements.txt"  # Вказуємо шлях до файлу з залежностями
