version: 2

build:
  image: "ubuntu-20.04"  # Замініть на одну з підтримуваних версій
  os: "ubuntu-20.04"     # Використовуйте правильну версію ОС
  tools:
    python: "3.8"

# Додавання статичного сайту (Swagger UI або Redoc)
static:
  html: "index.html"
