name: Update OpenAPI

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-openapi:
    runs-on: ubuntu-latest

    steps:
      # 1.  лонуЇмо з ус≥Їю ≥стор≥Їю (fetch-depth: 0)
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # <- ¬ј∆Ћ»¬ќ

      # 2. (опц≥йно) робимо pull --rebase, €кщо хочемо гарантовано Уп≥дт€гнутиФ найсв≥ж≥ш≥ зм≥ни
      - name: Pull changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git pull --rebase origin main

      - name: Fetch openapi.json
        run: |
          # ваш≥ команди curl
          echo "..."

      - name: Commit changes
        run: |
          # ваш≥ команди git add / commit
          echo "..."

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
