name: Update OpenAPI from API2Cart

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-openapi:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # ВАЖЛИВО, отримує всю історію, а не тільки останній коміт

      - name: Pull remote changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          # Підтягуємо оновлення, якщо паралельно були нові коміти в master
          git pull --rebase origin master

      - name: Fetch openapi files
        run: |
          # Ваші curl для завантаження файлів
          echo "curl -fSLo openapi.json https://app.api2cart.com/openapi/openapi.json"
            # Завантажуємо мовні openapi-файли
          curl -fSLo de/de_openapi.json https://app.api2cart.com/openapi/de_openapi.json
          curl -fSLo es/es_openapi.json https://app.api2cart.com/openapi/es_openapi.json
          curl -fSLo it/it_openapi.json https://app.api2cart.com/openapi/it_openapi.json
          curl -fSLo fr/fr_openapi.json https://app.api2cart.com/openapi/fr_openapi.json
          # ... тощо

      - name: Commit changes
        run: |
          # Перевіряємо, чи є зміни, і комітимо
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Update openapi.json automatically"
          else
            echo "No changes to commit."
          fi

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
