name: Update OpenAPI from API2Cart

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-openapi:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # ÂÀÆËÈÂÎ, îòðèìóº âñþ ³ñòîð³þ, à íå ò³ëüêè îñòàíí³é êîì³ò

      - name: Pull remote changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          # Ï³äòÿãóºìî îíîâëåííÿ, ÿêùî ïàðàëåëüíî áóëè íîâ³ êîì³òè â master
          git pull --rebase origin master

      - name: Fetch openapi files
        run: |
          # Âàø³ curl äëÿ çàâàíòàæåííÿ ôàéë³â
          echo "curl -fSLo openapi.json https://app.api2cart.com/openapi/openapi.json"
            # Çàâàíòàæóºìî ìîâí³ openapi-ôàéëè
          curl -fSLo de/openapi.json https://app.api2cart.com/openapi/de_openapi.json
          curl -fSLo es/openapi.json https://app.api2cart.com/openapi/es_openapi.json
          curl -fSLo it/openapi.json https://app.api2cart.com/openapi/it_openapi.json
          curl -fSLo fr/openapi.json https://app.api2cart.com/openapi/fr_openapi.json
          curl -fSLo openapi.json https://app.api2cart.com/openapi/openapi.json
          # ... òîùî

      - name: Commit changes
        run: |
          # Ïåðåâ³ðÿºìî, ÷è º çì³íè, ³ êîì³òèìî
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Update openapi.json automatically"
          else
            echo "No changes to commit."
          fi

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
